import { Inter } from "next/font/google";
import "./globals.css";
import { VedioLogo } from "../../components/VedioLogo";
import { Navbar } from "../../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body classNameName={inter.className}>{children}
      <Navbar/>
</body>

    </html>
  );
}
